RelayMotorInsuranceCalculator/ViewModels/ClaimVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RelayMotorInsuranceCalculator.ViewModels
{
    public class ClaimVm
    {
    }
}

RelayMotorInsuranceCalculator/ViewModels/DriverVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RelayMotorInsuranceCalculator.DAL.Entities.Enums;

namespace RelayMotorInsuranceCalculator.ViewModels
{
    public class DriverVm
    {
        public List<ClaimVm> Claims { get; set; }
        public PolicyVm Policy { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Occupation Occupation { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
}

RelayMotorInsuranceCalculator/ViewModels/MotorInsurance/ClaimVm.cs
using System;

namespace RelayMotorInsuranceCalculator.ViewModels.MotorInsurance
{
    public class ClaimVm
    {
        public DriverVm Driver { get; set; }
        public DateTime ClaimDate { get; set; }
    }
}

RelayMotorInsuranceCalculator/ViewModels/MotorInsurance/DriverVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using RelayMotorInsuranceCalculator.DAL.Entities.Enums;

namespace RelayMotorInsuranceCalculator.ViewModels.MotorInsurance
{
    public class DriverVm
    {
        public List<ClaimVm> Claims { get; set; }
        public PolicyVm Policy { get; set; }
        [Required]
        [MinLength(3)]
        [MaxLength(30)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Please enter a valid name")]
        public string Name { get; set; }
        
        [Required]
        public Occupation Occupation { get; set; }
        [Required]
        public DateTime DateOfBirth { get; set; }
    }
}

RelayMotorInsuranceCalculator/ViewModels/MotorInsurance/PolicyVm.cs
using System;
using System.Collections.Generic;

namespace RelayMotorInsuranceCalculator.ViewModels.MotorInsurance
{
    public class PolicyVm
    {
        public List<DriverVm> Drivers { get; set; }
        public DateTime StartDate { get; set; }
    }
}

RelayMotorInsuranceCalculator/ViewModels/MotorInsurance/PremiumCalculatorVm.cs
namespace RelayMotorInsuranceCalculator.ViewModels.MotorInsurance
{
    public class PremiumCalculatorVm
    {
        public PolicyVm Policy { get; set; }
    }
}

RelayMotorInsuranceCalculator/ViewModels/PolicyVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RelayMotorInsuranceCalculator.ViewModels
{
    public class PolicyVm
    {
        public List<DriverVm> Drivers { get; set; }
        public DateTime StartDate { get; set; }
    }
}

RelayMotorInsuranceCalculator/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RelayMotorInsuranceCalculator.Controllers
{
    public class BaseController : Controller
    {
    }
}

RelayMotorInsuranceCalculator/Controllers/MotorInsuranceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using RelayMotorInsuranceCalculator.DAL.Entities;
using RelayMotorInsuranceCalculator.DAL.Entities.Enums;
using RelayMotorInsuranceCalculator.Extensions;
using RelayMotorInsuranceCalculator.Services;
using RelayMotorInsuranceCalculator.Services.Models.Enums;
using RelayMotorInsuranceCalculator.ViewModels;
using RelayMotorInsuranceCalculator.ViewModels.MotorInsurance;

namespace RelayMotorInsuranceCalculator.Controllers
{
    public class MotorInsuranceController : BaseController
    {
        private readonly IPremiumCalculationService _premiumCalculationService;
        private readonly IMapper _mapper;

        public MotorInsuranceController(IPremiumCalculationService premiumCalculationService, IMapper mapper)
        {
            _premiumCalculationService = premiumCalculationService;
            _mapper = mapper;
        }

        public ActionResult PremiumCalculator()
        {
            var vm = new PremiumCalculatorVm
            {
                Policy = new PolicyVm
                {
                    StartDate = DateTime.Today,
                    Drivers = new List<DriverVm>
                    {
                        new DriverVm
                        {
                            DateOfBirth = DateTime.Today
                        }
                    }
                }
            };
            return View(vm);
        }
        
        [HttpPost]
        public ActionResult AddDriver(PremiumCalculatorVm vm)
        {
            vm.Policy.Drivers.Add(new DriverVm
            {
                DateOfBirth = DateTime.Today
            });
            ViewData.ModelState.Clear();
            return PartialView("_Drivers", vm);
        }

        [HttpPost]
        public ActionResult RemoveDriver(PremiumCalculatorVm vm, int index)
        {
            var driverToRemove = vm.Policy.Drivers[index];
            vm.Policy.Drivers.Remove(driverToRemove);
            ViewData.ModelState.Clear();
            return PartialView("_Drivers", vm);
        }

        [HttpPost]
        public ActionResult AddClaim(PremiumCalculatorVm vm, int index)
        {
            var driver = vm.Policy.Drivers[index];
            if (driver.Claims == null)
            {
                driver.Claims = new List<ClaimVm>
                {
                    new ClaimVm
                    {
                        ClaimDate = DateTime.Today
                    }
                };
            }
            else
            {
                driver.Claims.Add(new ClaimVm
                {
                    ClaimDate = DateTime.Today
                });
            }
            ViewData.ModelState.Clear();
            return PartialView("_Drivers", vm);
        }

        [HttpPost]
        public ActionResult RemoveClaim(PremiumCalculatorVm vm, int driver, int claim)
        {
            var claimToRemove = vm.Policy.Drivers[driver].Claims[claim];
            vm.Policy.Drivers[driver].Claims.Remove(claimToRemove);
            ViewData.ModelState.Clear();
            return PartialView("_Drivers", vm);
        }

        [HttpPost]
        public JsonResult Calculate(PremiumCalculatorVm vm)
        {
            var policy = _mapper.Map<Policy>(vm.Policy);
            var declined = _premiumCalculationService.DetermineIfPolicyShouldBeDeclined(policy);
            if (!declined.PolicyDeclined)
            {
                var premium = _premiumCalculationService.CalculatePremium(policy);
                ViewData.ModelState.Clear();
                return Json(new { message = $"Your policy premium will be: £{decimal.Round(premium,2)}", messageType = "success" });
            }
            string declineMessage = "";
            switch (declined.PolicyDeclineReason)
            {
                case PolicyDeclineReason.YoungestDriverTooYoung:
                    var youngestDriverName = vm.Policy.Drivers.OrderByDescending(o => o.DateOfBirth).First().Name;
                    declineMessage = declined.PolicyDeclineReason.GetDescription() + ' ' + youngestDriverName;
                    break;
                case PolicyDeclineReason.OldestDriverTooOld:
                    var oldestDriverName = vm.Policy.Drivers.OrderBy(o => o.DateOfBirth).First().Name;
                    declineMessage = declined.PolicyDeclineReason.GetDescription() + ' ' + oldestDriverName;
                    break;
                case PolicyDeclineReason.SingleDriverMoreThanTwoClaims:
                    var driverWithTooManyClaims = vm.Policy.Drivers.Find(o => o.Claims.Count > 2).Name;
                    declineMessage = declined.PolicyDeclineReason.GetDescription() + ' ' + driverWithTooManyClaims;
                    break;
                case PolicyDeclineReason.TotalMoreThanThreeClaims:
                    declineMessage = declined.PolicyDeclineReason.GetDescription();
                    break;
                case PolicyDeclineReason.StartDateBeforeCurrentDate:
                    declineMessage = declined.PolicyDeclineReason.GetDescription();
                    break;
            }
            ViewData.ModelState.Clear();
            return Json(new { message = $"Unfortunately your policy has been declined with the reason: {declineMessage}", messageType = "danger" });
        }
    }
}

RelayMotorInsuranceCalculator/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

RelayMotorInsuranceCalculator/Views/MotorInsurance/EditorTemplates/ClaimVm.cshtml
@model RelayMotorInsuranceCalculator.ViewModels.MotorInsurance.ClaimVm

<div class="col-md-4" style="margin-top: 7px">
    Date of claim
</div>
<div class="col-md-6">
    <div class="form-group">
        <div class='input-group date claimdatepicker'>
            @Html.EditorFor(o => o.ClaimDate, new { htmlAttributes = new { @class = "form-control" } })
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>
    @Html.ValidationMessageFor(o => o.ClaimDate, "", new { @class = "text-danger" })
</div>

RelayMotorInsuranceCalculator/Views/MotorInsurance/EditorTemplates/DriverVm.cshtml
@model RelayMotorInsuranceCalculator.ViewModels.MotorInsurance.DriverVm

<div class="row" style="margin-bottom: 15px">
    <div class="col-md-4" style="margin-top: 7px">
        Name
    </div>
    <div class="col-md-6">
        @Html.EditorFor(o => o.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(o => o.Name, "", new { @class = "text-danger", style = "margin-top:7px" })
    </div>
</div>
<div class="row" style="margin-bottom: 15px">
    <div class="col-md-4" style="margin-top: 7px">
        Occupation
    </div>
    <div class="col-md-6">
        @Html.EnumDropDownListFor(o => o.Occupation, new { @class = "form-control" })
        @Html.ValidationMessageFor(o => o.Occupation, "", new { @class = "text-danger", style = "margin-top:7px" })
    </div>
</div>

<div class="row">
    <div class="col-md-4" style="margin-top: 7px">
        Date of Birth
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <div class='input-group date agedatepicker'>
                @Html.EditorFor(o => o.DateOfBirth, new {htmlAttributes = new {@class = "form-control"}})
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        @Html.ValidationMessageFor(o => o.DateOfBirth, "", new { @class = "text-danger" })
    </div>
</div>

RelayMotorInsuranceCalculator/Views/MotorInsurance/PremiumCalculator.cshtml
@using RelayMotorInsuranceCalculator.DAL.Entities
@model RelayMotorInsuranceCalculator.ViewModels.MotorInsurance.PremiumCalculatorVm

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datepicker")
    <script src="/Scripts/Views/premium_calculator.js"></script>
}


<div class="row" style="margin-left: 10px; margin-bottom: 10px">
    <h2>Motor Insurance Premium Calculation</h2>
</div>
@using (Html.BeginForm("Calculate", "MotorInsurance", FormMethod.Post, new { id = "Form" }))
{
    <div class="row">
        <div class="col-md-2" style="margin-top: 7px;margin-left: 12px">
            Policy Start Date
        </div>
        <div class='col-md-2' style="margin-left: -7px;">
            <div class="form-group">
                <div class='input-group date datepicker'>
                    @Html.EditorFor(o => o.Policy.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top:25px">
        <div id="Drivers">
            @Html.Partial("_Drivers")
        </div>
    </div>
    <div class="row">
        <div id="message"></div>
        <div class="pull-right col-md-2">
            <button class="btn btn-default btn-primary" onclick="Calculate()" type="button">Calculate</button>
        </div>
    </div>
}

RelayMotorInsuranceCalculator/Views/MotorInsurance/_Drivers.cshtml
@model RelayMotorInsuranceCalculator.ViewModels.MotorInsurance.PremiumCalculatorVm

@for (int i = 0; i < Model.Policy.Drivers.Count; i++)
{
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Driver</h4>
                <div class="pull-right">
                    @if (i == Model.Policy.Drivers.Count - 1 && Model.Policy.Drivers.Count < 5)
                    {
                        <button class="btn btn-default btn-primary" onclick="AddDriver()" type="button">Add Driver</button>
                    }
                    @if (Model.Policy.Drivers.Count > 1)
                    {
                        <button class="btn btn-danger btn-sm" type="button" onclick="RemoveDriver('@i');"><span class="glyphicon glyphicon-remove"></span></button>
                    }
                </div>
            </div>
            <div class="panel-body">
                @Html.EditorFor(o => o.Policy.Drivers[i])
                @if (Model.Policy.Drivers[i].Claims?.Count > 0)
                {
                    <h3>Claims</h3>
                    for (int j = 0; j < Model.Policy.Drivers[i].Claims.Count; j++)
                    {
                        <div class="row">
                            @Html.EditorFor(o => o.Policy.Drivers[i].Claims[j])
                            <div class="col-md-2">
                                <button class="btn btn-danger btn-sm" type="button" onclick="RemoveClaim('@i', '@j');"><span class="glyphicon glyphicon-remove"></span></button>
                            </div>
                        </div>
                    }
                }
                @if (Model.Policy.Drivers[i].Claims == null || Model.Policy.Drivers[i].Claims.Count < 5)
                {
                    <div class="row">
                        <button class="btn btn-default btn-primary" style="margin-left: 10px" onclick="AddClaim('@i')" type="button">Add Claim</button>
                    </div>
                }
            </div>
        </div>

    </div>
}

RelayMotorInsuranceCalculator/Views/Shared/_Alert.cshtml
<script>
    function ShowAlert(type, message) {
        $('#alertArea').html("<div class='alert alert-dismissible' role='alert' id='alertMessage'><button type='button' class='close' data-dismiss='alert' id='alertDismiss'><span>&times;</span></button></div>");
        $('#alertMessage').addClass('alert-' + type);
        $('#alertMessage').append(message);
        window.scrollTo(0, 0);
    }
    function DismissAlert() {
        $('#alertDismiss').click();
    }
</script>

RelayMotorInsuranceCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Motor Insurance Calculation</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Motor Insurance Calculation", "PremiumCalculator", "MotorInsurance", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="alertArea">
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Carlo Hagens</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @Html.Partial("_Alert");
    @RenderSection("scripts", required: false)
</body>
</html>